# site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: https://aolabs.dev
title: AO Labs
landing-title: Hello, Welcome to my website.
author: Blacksuan19
description: I'm a data scientist by day and an all around tech enthusiast by night. I write about my experiences, projects and occasionally solutions.
about-text:

# address settings
street_address:
city: Greater Chicago Area
state: IL
zip_code:
country: United States

# homepage config
tiles-count: 3 # number of tiles on home page
post-tiles: true # whether to show post tiles
projects-tiles: true # whether to show project tiles
home-about: false # whether to show about-text in home page or contact page

# social settings
email: me@aolabs.dev
disqus: "blacksuan19-me" # comments on blog posts
formspree: https://formspree.io/f/xpzoedna # contact form target
preferred_contact: linkedin # social media to show on contact page

# add social media links here and they will show up in the footer
# icon: url
social_urls:
  linkedin: https://www.linkedin.com/in/blacksuan19/
  github: https://github.com/blacksuan19
  kaggle: https://www.kaggle.com/abubakaryagob/
  telegram: https://t.me/blacksuan19
  android: https://forum.xda-developers.com/member.php?u=5980272
  # instagram:
  # twitter:
  # facebook:
  # pinterest:

# skills widget
skills:

# page groups settings (groups pages with group = true in nav menu)
group_pages: true
group_name: Significant Projects

# external links to be added to the bottom of the menu
# label for the header
extern_name: External Links

# URLs, format name:url
extern_urls:
  Redash-Python library: https://redash.aolabs.dev/
  Stanford ML Notes: https://kutt.it/u7MfXU
  Deep Learning Notes: https://kutt.it/kJ5UOf

# build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed

# custom directory to fetch pages from
include: ["_pages"]
collections:
  pages:
    output: true
    permalink: "/:path"

# remove dates and prettify links
permalink: pretty

# jekyll admin settings
jekyll_admin:
  hidden_links:
    - datafiles

lsi: true
